---
- name: "main"
  hosts: myhosts
  
  tasks:
    - name: "know cpu usage"
      win_powershell:
        script: wmic cpu get loadpercentage
      register: "cpu"
   
    - name: "know Total memory available"
      win_powershell:
        script: systeminfo | find "Total Physical Memory" 
      register: "ram_tot"
      
    - name: "know Available memory available"
      win_powershell:
        script: systeminfo | find "Available Physical Memory" 
      register: "ram_avail"
    
    - name: "know Diskspace Details"
      win_powershell:
        script: Get-PSDrive -PSProvider FileSystem | select Name, Root,@{n="Percent Free";e={([math]::Round($_.Free/($_.Used+$_.Free),2))*100}}
      register: "diskspace_details"
    
    - name: "know services status"
      win_powershell:
        script: Get-Service
      register: "services_details"
